### ISSUE TITLE
memset(pInterfaces, sizeof(pInterfaces), 0);

### ISSUE THREAD

**Issue by x893** [kamwar/simlabTrace#1]
Hi,

at91lib/usb/device/core/USBDDriver.c:501:9: error: 'memset' used with constant zero length parameter; this could be due to transposed parameters [-Werror=memset-transposed-args]
         memset(pInterfaces, sizeof(pInterfaces), 0);

**Comment by bodziow** [comment]
Thanks for reporting this issue.
Actually, this is a bug. Parameters were passed in the wrong order, should be:
`memset(pInterfaces, 0, sizeof(pInterfaces));`
With the current implementation, the program will not enter that part, but anyway, it will be fixed at the earliest opportunity.

**Comment by gavz** [comment]
> Thanks for reporting this issue. Actually, this is a bug. Parameters were passed in the wrong order, should be: `memset(pInterfaces, 0, sizeof(pInterfaces));` With the current implementation, the program will not enter that part, but anyway, it will be fixed at the earliest opportunity.

after this `memset(pInterfaces, 0, sizeof(pInterfaces));` i got an error : 
error: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess

but after this `memset(pInterfaces, 0, sizeof(*pInterfaces));`all ok
